/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Com_index: typeof import('./../../common/components/comIndex/Com_index.vue')['default']
    Dawosi_index: typeof import('./components/Dawosi_index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestAirPower: typeof import('./components/TestAirPower.vue')['default']
    TestAssets: typeof import('./components/TestAssets.vue')['default']
    TestFunction: typeof import('./components/TestFunction.vue')['default']
  }
}
